---
name: lint
on:
  workflow_dispatch:

  push:
    branches: [develop]
  pull_request: {}

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    container:
      image: cytopia/yamllint:latest
    steps:
      - name: Setup Node
        run: |
          apk add --update npm

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run yamllint
        run: |
          yamllint .

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:latest
    steps:
      - name: Setup Node
        run: |
          apk add --update npm

      - name: Checkout
        uses: actions/checkout@v6

      - name: Run shellcheck
        run: |
          set -euo pipefail
          find . -type f -name '*.sh' -not -path './node_modules/*' -print0 \
            | xargs -0 -r shellcheck
